### ISSUE TITLE
🌐 Implement REST API for Programmatic Access

### ISSUE THREAD

**Issue by loonghao** [loonghao/installer-analyzer#19]
## Overview

Implement a REST API to provide programmatic access to the installer analysis functionality. This will enable integration with CI/CD pipelines, web applications, and other automated systems.

## Current State

- ✅ Basic API module structure exists (`src/api/mod.rs`)
- ✅ Configuration types defined
- ❌ No actual API implementation
- ❌ No HTTP server
- ❌ No API endpoints

#### Analysis Endpoints
- `POST /api/v1/analyze` - Upload and analyze installer file
- `GET /api/v1/analyze/{id}` - Get analysis status
- `GET /api/v1/analyze/{id}/result` - Get analysis results
- `DELETE /api/v1/analyze/{id}` - Cancel/delete analysis

#### Sandbox Endpoints
- `POST /api/v1/sandbox` - Start sandbox analysis
- `GET /api/v1/sandbox/{id}` - Get sandbox status
- `GET /api/v1/sandbox/{id}/result` - Get sandbox results

#### Utility Endpoints
- `GET /api/v1/formats` - List supported formats
- `GET /api/v1/health` - Health check
- `GET /api/v1/version` - API version info

### Features

- [ ] **File Upload**: Support multipart file uploads
- [ ] **Async Processing**: Background job processing
- [ ] **Progress Tracking**: Real-time analysis progress
- [ ] **Multiple Formats**: Support JSON, HTML, Markdown output
- [ ] **Authentication**: API key or token-based auth
- [ ] **Rate Limiting**: Prevent API abuse
- [ ] **Swagger/OpenAPI**: API documentation

### Framework Choice
- **Recommended**: `axum` - Modern, fast, and well-integrated with tokio
- **Alternative**: `warp` or `actix-web`

### Dependencies to Add
```toml
# HTTP server
axum = "0.7"
tower = "0.4"
tower-http = { version = "0.5", features = ["fs", "cors", "trace"] }

# Serialization
serde_json = "1.0"

# File upload
multipart = "0.18"
tempfile = "3.0"

# Background jobs
tokio = { version = "1.0", features = ["full"] }

# API documentation
utoipa = "4.0"
utoipa-swagger-ui = "4.0"
```

### Architecture

```
API Layer
├── Routes (axum)
├── Handlers
├── Middleware (auth, cors, logging)
├── Background Jobs
└── Response Formatting
```

#### Analyze Installer
```http
POST /api/v1/analyze
Content-Type: multipart/form-data

{
  "file": <binary>,
  "format": "json",
  "options": {
    "extract_files": true,
    "analyze_registry": true
  }
}
```

```json
{
  "id": "550e8400-e29b-41d4-a716-446655440000",
  "status": "processing",
  "created_at": "2024-01-15T10:30:00Z",
  "estimated_completion": "2024-01-15T10:32:00Z"
}
```

#### Get Results
```http
GET /api/v1/analyze/550e8400-e29b-41d4-a716-446655440000/result
```

```json
{
  "id": "550e8400-e29b-41d4-a716-446655440000",
  "status": "completed",
  "result": {
    "metadata": { ... },
    "files": [ ... ],
    "registry_operations": [ ... ]
  },
  "analysis_duration": "00:01:23",
  "completed_at": "2024-01-15T10:31:23Z"
}
```

### Phase 1: Basic API
1. Set up axum server with basic routing
2. Implement file upload endpoint
3. Integrate with existing analyzer
4. Basic JSON responses

### Phase 2: Advanced Features
1. Background job processing
2. Progress tracking
3. Multiple output formats
4. Error handling

### Phase 3: Production Features
1. Authentication
2. Rate limiting
3. API documentation
4. Monitoring and logging

### New Files
- `src/api/server.rs` - HTTP server setup
- `src/api/routes/` - API route handlers
- `src/api/handlers/` - Business logic handlers
- `src/api/middleware/` - Custom middleware
- `src/api/models/` - API request/response models
- `src/api/jobs.rs` - Background job processing

### Modified Files
- `src/api/mod.rs` - Update module structure
- `src/main.rs` - Add API server command
- `src/cli/mod.rs` - Add API server CLI command
- `Cargo.toml` - Add dependencies

## Configuration

```toml
[api]
host = "127.0.0.1"
port = 8080
max_file_size = "100MB"
max_concurrent_jobs = 10
auth_required = false
cors_origins = ["*"]
```

## Testing

- [ ] Unit tests for handlers
- [ ] Integration tests for endpoints
- [ ] Load testing
- [ ] API documentation tests

## Documentation

- [ ] OpenAPI/Swagger specification
- [ ] API usage examples
- [ ] Integration guides
- [ ] Rate limiting documentation

## Priority

**Medium-High** - Important for automation and integration

## Labels

- `enhancement`
- `api`
- `integration`
- `medium-priority`
